<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
    <!ELEMENT agenda (contacto*)>
    <!ELEMENT contacto (nombre, telefonoFijo*, telefonoMovil+) >
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT telefonoFijo (#PCDATA)>
    <!ELEMENT telefonoMovil (#PCDATA)>
]>
<agenda>
    <contacto>
        <nombre>Ayuntamiento</nombre>
        <telefonoFijo>010</telefonoFijo>
        <telefonoMovil>111</telefonoMovil>
    </contacto>
    <contacto>
        <nombre>Emergencias</nombre>
        <telefonoMovil>Desconocido</telefonoMovil>
    </contacto>
</agenda>