<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escritores [
    <!ELEMENT escritores (escritor*)>
    <!ELEMENT escritor (nombre, naciemiento)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT naciemiento (#PCDATA)>
]>
<escritores>
    <escritor>
        <nombre>Mario Vargas Llosa</nombre>
        <naciemiento>28 de marzo de 1936</naciemiento>
    </escritor>
    <escritor>
        <nombre>Milar Kundera</nombre>
        <naciemiento>1 de abril de 1929</naciemiento>
    </escritor>
</escritores>